### ISSUE TITLE
serial

### ISSUE THREAD

**Issue by driekes1984** [voroshkov/Solo-DIY-RF-Laptimer#7]
Keep getting 'Serial' was not declared in this scope
Why?

#define TO_HEX(i) (i <= 9 ? 0x30 + i : 0x41 + i - 10)

void halfByteToHex(uint8_t *buf, uint8_t val) {
    buf[0] = TO_HEX((val & 0x0F));
}
void byteToHex(uint8_t *buf, uint8_t val) {
    halfByteToHex(buf, val >> 4);
    halfByteToHex(&buf[1], val);
}
void intToHex(uint8_t *buf, uint16_t val) {
    byteToHex(buf, val >> 8);
    byteToHex(&buf[2], val & 0x00FF);
}
void longToHex(uint8_t *buf, uint32_t val) {
    intToHex(buf, val >> 16);
    intToHex(&buf[4], val & 0x0000FFFF);
}

uint8_t send4BitsToSerial(uint8_t prefix, uint8_t byteValue) {
    if (Serial.availableForWrite() >= 3) {
        Serial.write(prefix);
        uint8_t buf;
        halfByteToHex(&buf, byteValue);
        Serial.write(buf);
        Serial.write('\n');
        return(1);
    }
    return(0);
}

uint8_t sendByteToSerial(uint8_t prefix, uint8_t byteValue) {
    if (Serial.availableForWrite() >= 4) {
        Serial.write(prefix);
        uint8_t buf[2];
        byteToHex(buf, byteValue);
        Serial.write(buf, 2);
        Serial.write('\n');
        return(1);
    }
    return(0);
}

uint8_t sendIntToSerial(uint8_t prefix, uint16_t intValue) {
    if (Serial.availableForWrite() >= 6) {
        Serial.write(prefix);
        uint8_t buf[4];
        intToHex(buf, intValue);
        Serial.write(buf, 4);
        Serial.write('\n');
        return(1);
    }
    return(0);
}

uint8_t sendLongToSerial(uint8_t prefix, uint8_t counter, uint32_t longValue) {
    if (Serial.availableForWrite() >= 12) {
        Serial.write(prefix);
        uint8_t buf[8];
        byteToHex(buf, counter);
        Serial.write(buf, 2);
        longToHex(buf, longValue);
        Serial.write(buf, 8);
        Serial.write('\n');
        return(1);
    }
    return(0);
}

**Comment by voroshkov** [comment]
Maybe you're trying to compile this file as a standalone one? 
In my project it's included in .ino, where Serial is defined.

**Comment by driekes1984** [comment]
No i am jusing the .ino to complile.

I am a real newbie at this so  im sorry if i sound stupid.

**Comment by voroshkov** [comment]
What version of Arduino IDE do you use?

**Comment by driekes1984** [comment]
I believe 1.6.4

**Comment by voroshkov** [comment]
1. Download repository
2. Unzip to temp folder
3. Go to .../Solo-DIY-RF-Laptimer-master/Arduino/solo-diy-rf-laptimer 
4. Open solo-diy-rf-laptimer.ino with Arduino IDE
5. In IDE select Tools -> Board -> "Arduino Pro or Pro Mini" (if you use this board, of course)
6. Select Tools -> Processor -> "Atmega328 (5V 16MHz)"
7. Select Sketch -> Verify/Compile
Done. Without any compilation issues.

**Comment by driekes1984** [comment]
Ok ill try that thanx

**Comment by driekes1984** [comment]
I updated my IDE to 1.8.1 now it works thank you very mutch

**Comment by voroshkov** [comment]
I have 1.6.7. which also works fine. 
I guess your previous Arduino installation was corrupted somehow.

**Comment by driekes1984** [comment]
Yeh maby but thanks anyway i realy like this build
